### ISSUE TITLE
Zookeeper locking

### ISSUE THREAD

**Issue by vincentbernat** [pyr/warp#11]
It would be nice to be able to place a lock to prevent parallel executions of some tasks. For example, for a task upgrading a cluster, it is usually unwanted to take place in parallel.

**Comment by pyr** [comment]
The RPC server as a spof could make for a weak locking server

**Comment by vincentbernat** [comment]
In the future, we'll have to be able to express something like "do this operation only on one server of a given group at the time". For example, I would prefer not to run "apt-get upgrade" on all the servers at the same time. Some kind of roll out functions with serialization in a given group, but groups done on parallel.

When I say in the future, this is somewhere between tomorrow and the next day. So, no need for tonight.

**Comment by pyr** [comment]
Agreed. I think two things will be needed:

- `barriers` to synchronize at the end of a step
- `sequences` to execute a command in sequence over a cluster

Ideally, this should also work beyond just the RPC server and allow targetting zookeeper for instance.
Please don't submit your PR implementing this before noon tomorrow, I might not have time to review it before then.
